# Generated by Django 4.1.5 on 2023-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображения'), ('table', 'Таблица')], max_length=25)),
            ],
        ),
    ]
