# Generated by Django 4.1.5 on 2023-01-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev1C', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('page', models.CharField(choices=[('home', 'Главная'), ('demand', 'Востребованность'), ('areas', 'География'), ('skills', 'Навыки'), ('vacancies', 'Последние вакансии')], max_length=25)),
                ('style', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dev1C.block'),
        ),
    ]
