# Generated by Django 4.1.5 on 2023-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev1C', '0002_block_content_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Содержание блока', 'verbose_name_plural': 'Содержания блока'},
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
