# Generated by Django 4.1.5 on 2023-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev1C', '0003_alter_block_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображения'), ('table', 'Таблица'), ('list', 'Список')], max_length=25),
        ),
    ]
