# Generated by Django 4.1.5 on 2023-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev1C', '0004_block_title_style_alter_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title_style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
